version: '3.8'

services:
  todolist-app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    container_name: todolist-container

